Make the crate no_std-compatible
Even though the crate doesn’t use std crate, because it doesn’t
declare `#![no_std]` it cannot be compiled in no_std environments:

    error[E0463]: can't find crate for `std`
      = note: the `thumbv6m-none-eabi` target may not support the standard library
      = note: `std` is required by `forward_ref` because it does not declare `#![no_std]`

Adding the annotation makes it possible to use the crate on no_std
targets.

Issue: https://github.com/CosmWasm/cosmwasm/issues/1484